<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLcmli08\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLcmli08/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLcmli08.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLcmli08\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLcmli08\appDevDebugProjectContainer([
    'container.build_hash' => 'Lcmli08',
    'container.build_id' => 'e63297c3',
    'container.build_time' => 1668971175,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLcmli08');
