<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBemnkhc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBemnkhc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBemnkhc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBemnkhc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBemnkhc\appDevDebugProjectContainer([
    'container.build_hash' => 'Bemnkhc',
    'container.build_id' => '89cff3a0',
    'container.build_time' => 1670780858,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBemnkhc');
