<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF7arp2r\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF7arp2r/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF7arp2r.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF7arp2r\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerF7arp2r\appDevDebugProjectContainer([
    'container.build_hash' => 'F7arp2r',
    'container.build_id' => '261a9310',
    'container.build_time' => 1667329661,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF7arp2r');
